#!/bin/sh

# clash core tests

. "${CLASH_ROOT-.}"/test/testlib/assert || exit

bin=./sed-bin

s() {
  input="$1"; shift
  printf %s "$input" | "$bin" "$@" | head -c -1
}

# Replace by smaller
assert_out s 'Hello World' 'Hell' 'Y' -- 'Yo World' # start
assert_out s 'Hello World' 'llo W' 'y w' -- 'Hey world' # middle
assert_out s 'Hello World' ' World' '!' -- 'Hello!' # end
# Replace by bigger
assert_out s 'Hello World' 'Hello' 'What in the' -- 'What in the World' # start
assert_out s 'Hello World' 'o' ' what is wrong with this' -- 'Hell what is wrong with this World' # middle
assert_out s 'Hello World' 'ld' 'k! Oh no :(' -- 'Hello Work! Oh no :(' # end
# Replace by same size
assert_out s 'Hello World' 'Hello' 'Yolo!' -- 'Yolo! World' # start
assert_out s 'Hello World' 'o' 'a' -- 'Hella World' # middle
assert_out s 'Hello World' 'ld' 'k!' -- 'Hello Work!' # end

# With regex
assert_out s 'Hello World' '[hH]' 'Well h' -- 'Well hello World' # start
assert_out s 'Hello World' '. .' 'a-w' -- 'Hella-world' # middle
assert_out s 'Hello World' 'o.*' '!' -- 'Hell!' # end
assert_out s 'Hello World' '.*' '' -- '' # full
assert_out s 'Hello World' '.*' 'Bye' -- 'Bye' # full
assert_out s 'Hello World' '[Hh]ello.* World*' '' -- '' # full

assert_out s 'Hello World' 'Hello World' 'Bye' -- 'Bye' # full
assert_out s 'Hello World' 'Hello World' '' -- '' # full

# Fail
assert_out s 'Hello World' 'xz' 'nope' -- 'Hello World' # end

# Back refs
assert_out s 'Hello World' '\([^ ]*\)' '\1! \1' -- 'Hello! Hello World'
assert_out s 'Hello World' '\([^ ]*\) \(.\)' '\1! \2 ' -- 'Hello! W orld'

assert_out s 'Hello World' '.*r' '& & &' -- 'Hello Wor Hello Wor Hello World'

# g opt
assert_out s 'Hello World' 'o' 'a' 'g' -- 'Hella Warld'
assert_out s 'Hello World' 'o' 'abocde' 'g' -- 'Hellabocde Wabocderld'
assert_out s 'Hello World' 'o' ' yo' 'g' -- 'Hell yo W yorld'
assert_out s 'Oh damn god damnit' 'damn' 'no' 'g' -- 'Oh no god noit'
assert_out s 'Oh damn god damnit' 'damn' 'n' 'g' -- 'Oh n god nit'
assert_out s 'Hello World' '.*' 'Bye' 'g' -- 'Bye' # full
assert_out s 'Hello World' '\([^ ]*\)' '\1! \1' 'g' -- 'Hello! Hello World! World'

end_tests
